CREATE OR REPLACE DYNAMIC TABLE DEV__MODELLING.CANCER__CWT.CWT_PERFORMANCE (
    RECORD_ID VARCHAR,
	PER_DATE_YEAR NUMBER,
	PER_DATE_MONTH NUMBER,
	PER_ORG_TRUST VARCHAR,
	PER_ORG_SITE VARCHAR,
	PER_ORG_NCL BOOLEAN,
	PER_METRIC VARCHAR,
	PER_VALUE NUMBER,
	PER_NUMERATOR FLOAT,
	PER_DENOMINATOR FLOAT
)
COMMENT="Dynamic table containing performance metrics for CWT data."
TARGET_LAG = "2 hours"
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
WAREHOUSE = NCL_ANALYTICS_XS
AS
--CTE to get parent organisation for site columns
WITH org_par AS (
    SELECT child."Organisation_Code" AS "ORG_SITE", par."Organisation_Code" AS "ORG_TRUST"
    FROM "Dictionary"."dbo"."Organisation" child

    LEFT JOIN "Dictionary"."dbo"."Organisation" par 
    ON child."SK_OrganisationID_ParentOrg" = par."SK_OrganisationID"
)

--Combine Performance metrics into 1 table
SELECT per_base.*
FROM (
	--2WW
	SELECT * FROM DEV__MODELLING.CANCER__CWT.CWT_PERFORMANCE_2WW
	UNION ALL
	--FDS
	SELECT * 
	FROM DEV__MODELLING.CANCER__CWT.CWT_PERFORMANCE_FDS 
	UNION ALL

	--62 Day, 38 Day, 24 Day
	SELECT * EXCLUDE (D62_ACC_DIAGNOSTIC, D62_ACC_TREATMENT, D62_ALLOCATIONMETHOD, D62_6S_SCENARIO)
	FROM DEV__MODELLING.CANCER__CWT.CWT_PERFORMANCE_62DAY
) per_base

LEFT JOIN DEV__MODELLING.CANCER__CWT.CWT_PATHWAY pw
ON per_base.RECORD_ID = pw.RECORD_ID

WHERE pw.PATHWAY != 'Unknown'

UNION ALL
--Handle 31 Day seperately since the records are not dependant on standard pathway options
--31 Day
SELECT * FROM DEV__MODELLING.CANCER__CWT.CWT_PERFORMANCE_31DAY_FIRST
UNION ALL
SELECT * EXCLUDE D31_BREAKDOWN 
FROM DEV__MODELLING.CANCER__CWT.CWT_PERFORMANCE_31DAY_SUBSEQUENT