CREATE OR REPLACE DYNAMIC TABLE DATA_LAB_NCL_TRAINING_TEMP.CANCER_CWT.CWT_PERFORMANCE (
    RECORD_ID VARCHAR,
	PER_DATE_YEAR NUMBER,
	PER_DATE_MONTH NUMBER,
	PER_ORG VARCHAR,
	PER_ORG_NCL BOOLEAN,
	PER_METRIC VARCHAR(3),
	PER_VALUE NUMBER,
	PER_NUMERATOR NUMBER,
	PER_DENOMINATOR NUMBER
)
COMMENT="Dynamic table containing performance metrics for CWT data."
TARGET_LAG = "2 hours"
REFRESH_MODE = INCREMENTAL
INITIALIZE = ON_CREATE
WAREHOUSE = NCL_ANALYTICS_XS
AS
SELECT * FROM DATA_LAB_NCL_TRAINING_TEMP.CANCER_CWT.CWT_PERFORMANCE_2WW
UNION ALL
SELECT * FROM DATA_LAB_NCL_TRAINING_TEMP.CANCER_CWT.CWT_PERFORMANCE_FDS