CREATE OR REPLACE DYNAMIC TABLE DATA_LAB_NCL_TRAINING_TEMP.CANCER_CWT.CWT_BASE (
    --Entry identifiers
    SK VARCHAR, --UUID for rows in the CWT0001 Source table
    RECORDID VARCHAR, --UUID for the referral (Not unique)

    --Organisation Fields
    ORG_ACCOUNTABLEINVESTIGATING VARCHAR, --Investigating org for 6 Scernarios
    ORG_CONSULTANTUPGRADE VARCHAR, --Investigating org for Upgrade pathway
    ORG_FIRSTSEEN VARCHAR, --Org where patient is first seen post referral
    ORG_PATIENTPATHWAYIDENTIFIERISSUER VARCHAR, --Org associated with the pathway ID
    ORG_ACCOUNTABLETREATING VARCHAR, --Treating Organisation

    --Breakdowns Fields
    CWT_PRIMARYDIAGNOSISICD VARCHAR, --Diagnosis code

    --GP Fields
    PC_PRACTICECODE CHAR(8), --GP Practice Code
    
    --Pathway Identifiers
    PATHWAY_PRIORITYTYPECODE NUMBER, --Identifier for pathway
    PATHWAY_CANCERTREATMENTEVENTTYPE CHAR(2), --Identifier for pathway
    PATHWAY_REFERRALTYPE CHAR(2), --Identifier for pathway
    PATHWAY_SOURCEOFREFERRALFOROUTPATIENT CHAR(2), --Identifier for pathway
    PATHWAY_CANCERTREATMENTMODALITY CHAR(2), --Identifier for pathway
    PATHWAY_CANCERCARESETTINGTREATMENT CHAR(2), --Identifier for admitted care

    --Date Fields
    DATE_DECISIONTOREFERDATE DATE, --Unused?
    DATE_CANCERREFERRALTOTREATMENTPERIODSTARTDATE DATE, --Date of referral
    DATE_CONSULTANTUPGRADEDATE DATE, --Date for start for consultant pathway
    DATE_DATEFIRSTSEEN DATE, --Date of first completed appointment post referral 
    DATE_FDSPATHWAYENDDATE DATE, --Date where cancer is confirmed or ruled out
    DATE_CANCERTREATMENTPERIODSTARTDATE DATE, --Date for 31 Clock Start
    DATE_TRANSFERTOTREATMENTDATE DATE, --Date between Investigation and Treatment windows
    DATE_TREATMENTSTARTDATE DATE, --Date for Treatment starts
    
    --Waiting Time Adjustment
    WTA_FIRSTSEENADJUSTMENT NUMBER, --Adjustment for First Seen TTE
    WTA_TREATMENTADJUSTMENT NUMBER, --Adjustment for Treatment TTE
    WTA_TREATMENTREASON VARCHAR, --Reason for adjustment for Treatment TTE
    
    --Record Events
    EVENT_DATEFIRSTSEEN NUMBER, --Flag if the record includes the 2WW Pathway
    EVENT_CANCERTREATMENTPERIOD NUMBER, --Flag if the record includes the 31D Pathway
    EVENT_FDS NUMBER, --Flag if the record includes the 28D Pathway
    EVENT_TREATMENTSTARTDATE NUMBER, --Flag if the record includes the 62D Pathway

    --Metadata
    META_SUBMISSIONID NUMBER --Numeric ID for the upload batch in the source

)
COMMENT="Dynamic table to use as an univserial base for CWT data."
TARGET_LAG = "2 hours"
REFRESH_MODE = INCREMENTAL
INITIALIZE = ON_CREATE
WAREHOUSE = NCL_ANALYTICS_XS
AS
SELECT
    --Entry identifiers
    cwt.SK,
    cwt.RECORDID AS RECORD_ID,
    --Organisation Fields
    cwt.ACCOUNTABLEINVESTIGATINGPROVIDER AS ORG_ACCOUNTABLEINVESTIGATING,
    cwt.ORGCONSUPGRADE AS ORG_CONSULTANTUPGRADE,
    cwt.ORGFIRSTSEEN AS ORG_FIRSTSEEN,
    cwt.ORGPPI AS ORG_PATIENTPATHWAYIDENTIFIERISSUER,
    cwt.ORGTREATSTART AS ORG_ACCOUNTABLETREATING,
    --Breakdowns Fields
    cwt.PRIMARYDIAGNOSISICD AS CWT_PRIMARYDIAGNOSISICD,
    --GP Fields
    cwt.PDS_GPCODE AS PC_PRACTICECODE,
    --Pathway Identifiers
    cwt.PRIORITYTYPECODE AS PATHWAY_PRIORITYTYPECODE,
    cwt.CANCERTREATMENTEVENTTYPE AS PATHWAY_CANCERTREATMENTEVENTTYPE,
    cwt.REFTYPE AS PATHWAY_REFERRALTYPE,
    cwt.SOURCEOFREFERRALFOROUTPATIENT AS PATHWAY_SOURCEOFREFERRALFOROUTPATIENT,
    cwt.CANCERTREATMENTMODALITY AS PATHWAY_CANCERTREATMENTMODALITY,
    cwt.CANCERCARESETTINGTREATMENT AS PATHWAY_CANCERCARESETTINGTREATMENT,
    --Date Fields
    cwt.DECTOREFDATE AS DATE_DECSIONTOREFERDATE,
    cwt.CRTPDATE AS DATE_CANCERREFERRALTOTREATMENTPERIODSTARTDATE, 
    cwt.CONSULTANTUPGRADEDATE AS DATE_CONSULTANTUPGRADEDATE, 
    cwt.DATEFIRSTSEEN AS DATE_DATEFIRSTSEEN,
    cwt.CANCERFASTERDIAGNOSISPATHWAYENDDATE AS DATE_FDSPATHWAYENDDATE,
    --cwt.MDTDATE AS DATE_MULTIDISCIPLINARYTEAMDISCUSSIONDATE,
    cwt.CANCERTREATMENTPERIODSTARTDATE AS DATE_CANCERTREATMENTPERIODSTARTDATE,
    cwt.TRANSFERTOTREATMENTDATE AS DATE_TRANSFERTOTREATMENTDATE,
    cwt.TREATMENTSTARTDATECANCER AS DATE_TREATMENTSTARTDATE,
    --Waiting Time Adjustments
    cwt.WAITINGTIMEADJUSTMENTFIRSTSEEN AS WTA_FIRSTSEENADJUSTMENT,
    cwt.WAITINGTIMEADJUSTMENTTREATMENT AS WTA_TREATMENTADJUSTMENT,
    cwt.WAITINGTIMEADJUSTMENTREASONTREATMENT AS WTA_TREATMENTREASON,
    --Metadata
    cwt."UniqSubmissionID" AS META_SUBMISSIONID,
    CASE WHEN cwt.DATEFIRSTSEEN IS NULL THEN 0 ELSE 1 END AS EVENT_DATEFIRSTSEEN,
    CASE WHEN cwt.CANCERTREATMENTPERIODSTARTDATE IS NULL THEN 0 ELSE 1 END AS EVENT_CANCERTREATMENTPERIOD,
    CASE WHEN cwt.CANCERFASTERDIAGNOSISPATHWAYENDDATE IS NULL THEN 0 ELSE 1 END AS EVENT_FDS,
    CASE WHEN cwt.TREATMENTSTARTDATECANCER IS NULL THEN 0 ELSE 1 END AS EVENT_TREATMENTSTARTDATE

FROM "Data_Store_Waiting".CWTDS."CWT001Data" cwt

LEFT JOIN DATA_LAB_NCL_TRAINING_TEMP.CANCER_CWT.CWT_LATESTSUBMISSION ls
ON cwt.SK = ls.SK

WHERE ls.META_LATESTRECORD = 1

