CREATE OR REPLACE DYNAMIC TABLE DEV__MODELLING.CANCER__CWT_PATHWAY.CWT_31DAYBREAKDOWN (
	
	--Description: Further breakdown fields for patients on the 62 Day pathway
    --Author: Jake Kealey

    RECORD_ID VARCHAR,
	D31_FIRST BOOLEAN, --If the row is a first or subsequent 31 Day pathway
	D31_BREAKDOWN VARCHAR --Subcategory of pathway 
)
COMMENT="Breakdown for 31 Day pathway records."
TARGET_LAG = "24 hours"
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
WAREHOUSE = NCL_ANALYTICS_XS
AS
SELECT RECORD_ID, True, 'First' 
FROM DEV__MODELLING.CANCER__CWT_PATHWAY.CWT_PERFORMANCE_31DAY_FIRST
UNION ALL
SELECT RECORD_ID, False,  D31_BREAKDOWN 
FROM DEV__MODELLING.CANCER__CWT_PATHWAY.CWT_PERFORMANCE_31DAY_SUBSEQUENT