CREATE OR REPLACE DYNAMIC TABLE DATA_LAB_NCL_TRAINING_TEMP.CANCER_CWT.CWT_62DAYBREAKDOWN (
    RECORD_ID VARCHAR,
	D62_ACC_DIAGNOSTIC VARCHAR,
	D62_ACC_TREATMENT VARCHAR,
    D62_ALLOCATIONMETHOD VARCHAR,
    D62_6S_SCENARIO NUMBER
)
COMMENT="Breakdown for 62 Day pathway records."
TARGET_LAG = "2 hours"
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
WAREHOUSE = NCL_ANALYTICS_XS
AS
SELECT RECORD_ID, D62_ACC_DIAGNOSTIC, D62_ACC_TREATMENT, D62_ALLOCATIONMETHOD, D62_6S_SCENARIO
FROM DATA_LAB_NCL_TRAINING_TEMP.CANCER_CWT.CWT_PERFORMANCE_62DAY
--Logic to prevent multiple rows per record
WHERE D62_ALLOCATIONMETHOD = 'Solo'
OR (
    PER_ORG_TRUST = D62_ACC_DIAGNOSTIC
    AND PER_METRIC = '62 Day')