CREATE OR REPLACE DYNAMIC TABLE DATA_LAB_NCL_TRAINING_TEMP.CANCER_CWT.CWT_PERFORMANCE (
    RECORD_ID VARCHAR,
	PER_DATE_YEAR NUMBER,
	PER_DATE_MONTH NUMBER,
	PER_ORG_TRUST VARCHAR,
	PER_ORG_SITE VARCHAR,
	PER_ORG_NCL BOOLEAN,
	PER_METRIC VARCHAR,
	PER_VALUE NUMBER,
	PER_NUMERATOR NUMBER,
	PER_DENOMINATOR NUMBER
)
COMMENT="Dynamic table containing performance metrics for CWT data."
TARGET_LAG = "2 hours"
REFRESH_MODE = INCREMENTAL
INITIALIZE = ON_CREATE
WAREHOUSE = NCL_ANALYTICS_XS
AS
--CTE to get parent organisation for site columns
WITH org_par AS (
    SELECT child."Organisation_Code" AS "ORG_SITE", par."Organisation_Code" AS "ORG_TRUST"
    FROM "Dictionary"."dbo"."Organisation" child

    LEFT JOIN "Dictionary"."dbo"."Organisation" par 
    ON child."SK_OrganisationID_ParentOrg" = par."SK_OrganisationID"
)

--Full SELECT to order columns
SELECT 
	RECORD_ID,
	PER_DATE_YEAR,
	PER_DATE_MONTH,
	org_par.ORG_TRUST AS PER_ORG_TRUST,
	PER_ORG AS PER_ORG_SITE,
	PER_ORG_NCL,
	PER_METRIC,
	PER_VALUE,
	PER_NUMERATOR,
	PER_DENOMINATOR

--Combine Performance metrics into 1 table
FROM (
	SELECT * FROM DATA_LAB_NCL_TRAINING_TEMP.CANCER_CWT.CWT_PERFORMANCE_2WW
	UNION ALL
	SELECT * FROM DATA_LAB_NCL_TRAINING_TEMP.CANCER_CWT.CWT_PERFORMANCE_FDS
	UNION ALL
	SELECT * FROM DATA_LAB_NCL_TRAINING_TEMP.CANCER_CWT.CWT_PERFORMANCE_31DAY_FIRST
	UNION ALL
	SELECT * EXCLUDE D31_BREAKDOWN 
	FROM DATA_LAB_NCL_TRAINING_TEMP.CANCER_CWT.CWT_PERFORMANCE_31DAY_SUBSEQUENT
) per

LEFT JOIN org_par
ON org_par.ORG_SITE = per.PER_ORG

--Combine 38 Day and 62 Day seperately since the org column is trust level and not site